#! /bin/sh

[ "${TRACE}" = YES ] && set -x && : "$0" "$@"


_fatal()
{
   echo "$0 fatal error: $*" >&2
   exit 1
}

[ -z "${MULLE_FSWATCH_REPLAY_FILE}" ] && _fatal "environment MULLE_FSWATCH_REPLAY_FILE must be set"
[ ! -f "${MULLE_FSWATCH_REPLAY_FILE}" ] && _fatal "\"${MULLE_FSWATCH_REPLAY_FILE}\" is missing"

cat "${MULLE_FSWATCH_REPLAY_FILE}"

