#! /usr/bin/env bash
#
#   Copyright (c) 2018 Nat! - Mulle kybernetiK
#   All rights reserved.
#
#   Redistribution and use in source and binary forms, with or without
#   modification, are permitted provided that the following conditions are met:
#
#   Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
#   Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
#   Neither the name of Mulle kybernetiK nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
#   THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#   AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#   IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#   ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#   LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#   CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#   SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#   INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#   CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#   ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#   POSSIBILITY OF SUCH DAMAGE.
#
[ "${TRACE}" = 'YES' -o "${MULLE_MONITOR_TRACE}" = 'YES' ] && set -x && : "$0" "$@"


MULLE_EXECUTABLE_VERSION=0.6.3

#
# This is the main user interface to mulle-monitor
#

trap_fail()
{
   exit 1
}


SHOWN_COMMANDS="\
   callback       : manage callbacks
   patternfile    : manage patternfiles
   task           : manage tasks
   run            : monitor files and run scripts"

HIDDEN_COMMANDS="\
   libexec-dir    : print path to mulle-monitor libexec
   uname          : mulle-monitors simplified uname(1)"


print_commands()
{
   local show_all="${1:-NO}"

   echo "${SHOWN_COMMANDS}"

   if [ "${show_all}" != 'NO' ]
   then
      echo "${HIDDEN_COMMANDS}"
   fi
}


print_hidden_flags()
{
   cat <<EOF
   --default-callback <command> : use 'echo <taskname>' to run only one task
   --config-dir <dir>           : set MULLE_MONITOR_DIR
   --ignore-dir <dir>           : set MULLE_MONITOR_IGNORE_DIR
   --match-dir <dir>            : set MULLE_MONITOR_MATCH_DIR
   --etc-dir <dir>              : set MULLE_MONITOR_ETC_DIR
   --var-dir <dir>              : set MULLE_MONITOR_VAR_DIR
EOF
}


print_flags()
{
   local show_all="${1:-NO}"

   local delimiter

   delimiter="                        : "

   if [ "${show_all}" != 'NO' ]
   then
      print_hidden_flags
   fi

   echo "   -e   ${delimiter}bypass mulle-env check"
   echo "   -f   ${delimiter}force operation"
   echo "   --sleep <delay>              : time to coalesce multiple events"

   options_technical_flags_usage "${delimiter}"
}


_usage()
{
   local verbose="${1:-NO}"
   local error="${2}"

   if [ ! -z "${error}" ]
   then
      log_error "${error}"
   fi

   cat <<EOF
Usage:
   ${MULLE_USAGE_NAME} [flags] [command]

   The filesystem monitor. Invokes callbacks based on changes to files. A
   callback may optionally invoke a task. Which callback is invoked, is based
   on patternfiles, which are .gitignore like rule files.

   A callback should be extremely short lived. A task can be long running.
   Multiple callbacks can coalesce to one task run, if they are appearing
   within the \`--sleep\` period.

Flags:
EOF
   print_flags "${verbose}" | LC_ALL=C sort


   cat <<EOF

Commands:
EOF

   print_commands "${verbose}" | LC_ALL=C sort

   if [ "${verbose}" = 'NO' ]
   then
      cat <<EOF
      (use mulle-monitor -v help to show more commands)
EOF
   fi

   cat <<EOF

   Use ${MULLE_USAGE_NAME} <command> -h for topical help.
EOF

   exit 1
}


usage()
{
   _usage "$@" >&2
   exit 1
}

#
# call only if needed
#
monitor_match_environment()
{
   log_entry "monitor_match_environment" "$@"

   local cmd="$1"

   MULLE_MONITOR_MATCH_ENVIRONMENT='YES'

   case "${MULLE_MONITOR_MATCH_DIR}" in
      NO)
         MULLE_MONITOR_MATCH_DIR=""
         log_fluff "Not using \"MULLE_MONITOR_MATCH_DIR\""
      ;;

      "")
         MULLE_MONITOR_MATCH_DIR="${MULLE_MONITOR_ETC_DIR}/match.d"
         if [ ! -d "${MULLE_MONITOR_MATCH_DIR}" ]
         then
            MULLE_MONITOR_MATCH_DIR="${MULLE_MONITOR_DIR}/share/match.d"
         fi
         if [ ! -d "${MULLE_MONITOR_MATCH_DIR}" ]
         then
         	if [ "${cmd}" != "clean" ]
         	then
	            log_warning "There is no directory \"${MULLE_MONITOR_MATCH_DIR#${PWD}/}\" set up"
            fi
            MULLE_MONITOR_MATCH_DIR=""
         fi
      ;;
   esac

   case "${MULLE_MONITOR_IGNORE_DIR}" in
      NO)
         MULLE_MONITOR_IGNORE_DIR=""
         log_fluff "Not using \"MULLE_MONITOR_IGNORE_DIR\""
      ;;

      "")
         MULLE_MONITOR_IGNORE_DIR="${MULLE_MONITOR_ETC_DIR}/ignore.d"
         if [ ! -d "${MULLE_MONITOR_IGNORE_DIR}" ]
         then
            MULLE_MONITOR_IGNORE_DIR="${MULLE_MONITOR_DIR}/share/ignore.d"
         fi
         if [ ! -d "${MULLE_MONITOR_IGNORE_DIR}" ]
         then
            log_fluff "There is no directory \"${MULLE_MONITOR_IGNORE_DIR#${PWD}/}\" set up"
            MULLE_MONITOR_IGNORE_DIR=""
         fi
      ;;
   esac

   if [ "${MULLE_FLAG_LOG_SETTINGS}" = 'YES' ]
   then
      log_trace2 "MULLE_MONITOR_MATCH_ENVIRONMENT='${MULLE_MONITOR_MATCH_ENVIRONMENT}'"
      log_trace2 "MULLE_MONITOR_MATCH_DIR='${MULLE_MONITOR_MATCH_DIR}'"
      log_trace2 "MULLE_MONITOR_IGNORE_DIR='${MULLE_MONITOR_IGNORE_DIR}'"
   fi
}


monitor_environment()
{
   log_entry "monitor_environment" "$@"

   if [ -z "${MULLE_MONITOR_DIR}" ]
   then
      log_fluff "MULLE_MONITOR_DIR default is .mulle-monitor"

      MULLE_MONITOR_DIR='.mulle-monitor'
   fi

   local RVAL

   r_absolutepath "${MULLE_MONITOR_DIR}"
   MULLE_MONITOR_DIR="${RVAL}"

   r_fast_dirname "${MULLE_MONITOR_DIR}"
   MULLE_MONITOR_PARENT_DIR="${RVAL}"

   MULLE_MONITOR_ETC_DIR="${MULLE_MONITOR_ETC_DIR:-${MULLE_MONITOR_DIR}/etc}"
   MULLE_MONITOR_VAR_DIR="${MULLE_MONITOR_VAR_DIR:-${MULLE_MONITOR_DIR}/var/${MULLE_HOSTNAME}}"

   MULLE_MONITOR_SLEEP_EXE=sleep

   if [ -z "${MULLE_MONITOR_SLEEP_TIME}" ]
   then
      case "${MULLE_UNAME}" in
         linux|darwin)
            MULLE_MONITOR_SLEEP_TIME="1" # "0.3s"
         ;;
      esac
   fi

   if [ "${MULLE_FLAG_LOG_SETTINGS}" = 'YES' ]
   then
      log_trace2 "MULLE_MONITOR_SLEEP_EXE='${MULLE_MONITOR_SLEEP_EXE}'"
      log_trace2 "MULLE_MONITOR_SLEEP_TIME='${MULLE_MONITOR_SLEEP_TIME}'"
      log_trace2 "MULLE_MONITOR_DIR='${MULLE_MONITOR_DIR}'"
      log_trace2 "MULLE_MONITOR_ETC_DIR='${MULLE_MONITOR_ETC_DIR}'"
      log_trace2 "MULLE_MONITOR_VAR_DIR='${MULLE_MONITOR_VAR_DIR}'"
   fi
}


main()
{
   local MULLE_FLAG_MAGNUM_FORCE='NO'

   # technical flags
   local MULLE_TRACE
   local MULLE_FLAG_EXEKUTOR_DRY_RUN='NO'
   local MULLE_FLAG_LOG_LOCAL='NO'
   local MULLE_FLAG_LOG_DEBUG='NO'
   local MULLE_FLAG_LOG_EXEKUTOR='NO'
   local MULLE_FLAG_LOG_FLUFF='NO'
   local MULLE_FLAG_LOG_SCRIPTS='NO'
   local MULLE_FLAG_LOG_SETTINGS='NO'
   local MULLE_FLAG_LOG_VERBOSE='NO'
   local MULLE_FLAG_LOG_MERGE='NO'
   local MULLE_TRACE_POSTPONE='NO'
   local MULLE_MONITOR_PREEMPT='YES'

   if [ -z "${MULLE_PATH_SH}" ]
   then
      # shellcheck source=mulle-path.sh
      . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-path.sh"      || return 1
   fi
   if [ -z "${MULLE_FILE_SH}" ]
   then
      # shellcheck source=mulle-file.sh
      . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-file.sh"      || return 1
   fi

   #
   # simple option handling
   #
   while [ $# -ne 0 ]
   do
      if options_technical_flags "$1"
      then
         shift
         continue
      fi

      case "$1" in
         -h*|--help|help)
            usage "${MULLE_TRACE}"
         ;;

         -e)
            FLAG_OUTSIDE_ENV='YES'
         ;;

         -f)
            MULLE_FLAG_MAGNUM_FORCE='YES'
         ;;

         --preempt)
            MULLE_MONITOR_PREEMPT='YES'
         ;;

         --no-preempt)
            MULLE_MONITOR_PREEMPT='NO'
         ;;

         -cd|--config-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "Missing argument to \"$1\""
            shift

            MULLE_MONITOR_DIR="$1"
         ;;

         --default-callback)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "Missing argument to \"$1\""
            shift

            MULLE_MONITOR_DEFAULT_CALLBACK="$1"
         ;;

         -ed|--etc-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "Missing argument to \"$1\""
            shift

            MULLE_MONITOR_ETC_DIR="$1"
         ;;

         -md|--match-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "Missing argument to \"$1\""
            shift

            MULLE_MONITOR_MATCH_DIR="$1"
         ;;

         -id|--ignore-dir)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "Missing argument to \"$1\""
            shift

            MULLE_MONITOR_IGNORE_DIR="$1"
         ;;

         --sleep)
            [ $# -eq 1 ] && usage "${MULLE_TRACE}" "Missing argument to \"$1\""
            shift

            MULLE_MONITOR_SLEEP_TIME="$1"
         ;;

         --var-tmp)
            r_make_tmp "mulle-monitor" "-d"
            MULLE_MONITOR_VAR_DIR="${RVAL}"
         ;;

         --version)
            echo "${MULLE_EXECUTABLE_VERSION}"
            exit 0
         ;;

         -*)
            log_error "Unknown option \"$1\""
            usage "${MULLE_TRACE}"
         ;;

         *)
            break
         ;;
      esac

      shift
   done

   options_setup_trace "${MULLE_TRACE}"

   local cmd

   cmd="$1"
   [ $# -ne 0 ] && shift

   local physdir

   physdir="`pwd -P`"

   if [ "${FLAG_OUTSIDE_ENV}" = 'YES' ]
   then
      MULLE_VIRTUAL_ROOT="${physdir}"
      [ "${MULLE_VIRTUAL_ROOT}" = "/" ] && fail "MULLE_VIRTUAL_ROOT must not be /"
      export MULLE_VIRTUAL_ROOT
   fi

   if [ -z "${MULLE_VIRTUAL_ROOT}" ]
   then
      case "${cmd}" in
         callback|find|match|run|task)
            fail "To run ${MULLE_EXECUTABLE_NAME} outside of mulle-env, \
pass the -e flag"
         ;;
      esac
   fi

   local rval

   monitor_environment 

   case "${cmd}" in
      help)
         usage "${MULLE_TRACE}"
      ;;

      callback)
         # shellcheck source=src/mulle-monitor-callback.sh
         . "${MULLE_MONITOR_LIBEXEC_DIR}/mulle-monitor-callback.sh"

         monitor_callback_main "$@"
      ;;

      clean|find|match|patternfile)
         monitor_match_environment "${cmd}"

         MULLE_USAGE_NAME="${MULLE_USAGE_NAME}" \
            exekutor "${MULLE_MATCH:-mulle-match}" \
                           ${MULLE_TECHNICAL_FLAGS} \
                           ${MULLE_MATCH_FLAGS} \
                           --ignore-dir "${MULLE_MONITOR_IGNORE_DIR}" \
                           --match-dir "${MULLE_MONITOR_MATCH_DIR}" \
                           --var-dir "${MULLE_MONITOR_VAR_DIR}" \
                        "${cmd}" \
                           "$@"
      ;;

      libexec-dir|library-path)
         echo "${MULLE_MONITOR_LIBEXEC_DIR}"
      ;;

      run)
         monitor_match_environment "${cmd}"

         # shellcheck source=src/mulle-monitor-run.sh
         . "${MULLE_MONITOR_LIBEXEC_DIR}/mulle-monitor-run.sh"

         monitor_run_main "$@"
      ;;

      task)
         # shellcheck source=src/mulle-monitor-task.sh
         . "${MULLE_MONITOR_LIBEXEC_DIR}/mulle-monitor-task.sh"

         monitor_task_main "$@"
      ;;

      uname)
         echo "${MULLE_UNAME}"
         return 0
      ;;

      version)
         echo "${MULLE_EXECUTABLE_VERSION}"
         return 0
      ;;

      "")
         MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE_NAME}"
         usage "${MULLE_TRACE}"
      ;;

      *)
         MULLE_EXECUTABLE_FAIL_PREFIX="${MULLE_EXECUTABLE_NAME}"
         log_error "Unknown command \"${cmd}\""
         usage "${MULLE_TRACE}"
      ;;
   esac
}


########
###
### INIT
###
_init()
{
   #
   # minimal setup exit
   #
   if [ "$1" = "version" ]
   then
      echo "${MULLE_EXECUTABLE_VERSION}"
      exit 0
   fi

   if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
   then
      MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir 2> /dev/null`"
      if [ -z "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}" ]
      then
         if [ -z "`command -v "${executablepath}"`" ]
         then
             echo "Fatal Error: Could not find mulle-bashfunctions-env in PATH (not installed ?)" >&2
         else
            echo "Fatal Error: Could not find libexec of mulle-bashfunctions-env ($PWD)" >&2
         fi
         exit 1
      fi
   fi

      # shellcheck source=../mulle-bashfunctions/src/mulle-string.sh
   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" "minimal" || \
      fail "failed to load bashfunctions from ${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}"

   local _libexec_dir

   _get_libexec_dir "$0" "mulle-monitor" "mulle-monitor-run.sh"

   MULLE_MONITOR_LIBEXEC_DIR="${_libexec_dir}"

   #
   # minimal setup exit
   #
   case "$1" in
      "libexec-dir"|"library-path")
         echo "${MULLE_MONITOR_LIBEXEC_DIR}"
         exit 0
      ;;
   esac

   #  set -e # more pain then gain in the end
   #  set -u # doesn't work with my style

   trap trap_fail INT
   set -o pipefail

   shopt -s extglob || internal_fail "Cant extglob"
}
###
### INIT
###
########


_init "$@" # needs params
main "$@"
