#! /usr/bin/env bash

[ "${TRACE}" = 'YES' ] && set -x && : "$0" "$@"

run_mulle_monitor()
{
   echo "####################################" >&2
   echo mulle-monitor ${MULLE_MONITOR_FLAGS} "$@"  >&2
   echo "####################################" >&2

   (
      MULLE_MONITOR_LIBEXEC_DIR="`${MULLE_MONITOR} libexec-dir`"

      . "${MULLE_MONITOR}" ${MULLE_MONITOR_FLAGS} "$@"
   )
}


expect_mulle_monitor()
{
   log_entry "expect_mulle_monitor" "$@"

   local expected="$1"; shift

   local result

   result="`run_mulle_monitor "$@"`" || fail "Failed unexpectedly"

   if [ "${result}" != "${expected}" ]
   then
      fail "Result \"${result}\" was expected to be \"${expected}\""
   fi
}


expect_failure_mulle_monitor()
{
   log_entry "expect_failure_mulle_monitor" "$@"

   local result

   if result="`run_mulle_monitor "$@"`"
   then
      fail "Did not fail unexpectedly"
   else
      log_info "Failed as expected"
   fi
}


main()
{
   MULLE_MONITOR_FLAGS="$@"

   _options_mini_main "$@" && set -x

   #-----------

   expect_mulle_monitor "${MULLE_EXECUTABLE_PWD}/.mulle/share/monitor/libexec/foo-task.sh" task locate foo

   log_verbose "----- #1 PASSED -----"

   #-----------

   expect_mulle_monitor "${MULLE_EXECUTABLE_PWD}/.mulle/share/monitor/libexec/bar-task.sh" task locate bar

   log_verbose "----- #2 PASSED -----"

   #-----------

   expect_failure_mulle_monitor task locate baz

   log_verbose "----- #3 PASSED -----"

   #-----------

   expect_mulle_monitor "" task test foo

   log_verbose "----- #4 PASSED -----"

   #-----------

   expect_failure_mulle_monitor task test bar

   log_verbose "----- #5 PASSED -----"

   #-----------



   log_info "----- ALL PASSED -----"
}



init()
{
   MULLE_BASHFUNCTIONS_LIBEXEC_DIR="`mulle-bashfunctions-env libexec-dir`" || exit 1

   . "${MULLE_BASHFUNCTIONS_LIBEXEC_DIR}/mulle-bashfunctions.sh" || exit 1

   MULLE_MONITOR="${MULLE_MONITOR:-${PWD}/../../mulle-monitor}"
}


init "$@"
main "$@"

